AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA Connect Customer Bucket

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pBucketSuffix:
    Type: String
    Description: Additional suffix for bucket name
  pClient:
    Type: String
    Description: Client name to be used in bucket name

Resources:
  ConnectS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-capita-${pDepartment}-${pClient}-${pEnvironmentLowerCase}${pBucketSuffix}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-connect"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "tech:ApplicationRole"
            Value: reporting
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment

Outputs:
  oConnectBucket:
    Value: !Ref ConnectS3Bucket