AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CAPITA Agent Events Bridge to Common Account

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pInputStreamName:
    Type: String
    Default: ccm
    Description: Arn of the input kinesis stream
  pClientName:
    Type: String
    Description: Environment variable of the lambda function
  pCommonAccountRoleArn:
    Type: String
    Description: Environment variable of the lambda function
  pTargetStreamName:
    Type: String
    Description: Environment variable of the lambda function
  pTargetStreamArn:
    Type: String
    Description: Arn of the target kinesis stream, used for IAM Policies

Resources:

  RtaBridgeLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lmbRTA-Bridge-${pDepartment}-${pEnvironment}"
      Handler: lambda_handler.handler
      Runtime: python3.6
      Timeout: 180
      CodeUri: ../src/bridge/code/
      Policies: 
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:DescribeStream
                - kinesis:ListStreams
              Resource: !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${pInputStreamName}"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - kinesis:PutRecords
                - kinesis:DescribeStream
                - kinesis:ListStreams
              Resource: !Ref pTargetStreamArn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: !Ref pCommonAccountRoleArn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: '*'
      Environment:
        Variables:
          Client_Name: !Ref pClientName
          Common_Account_Role_ARN: !Ref pCommonAccountRoleArn
          Target_Stream_Name: !Ref pTargetStreamName
      Tags:
          "tech:ApplicationID": !Sub "capita-${pDepartment}-rta-bridge"
          "tech:Environment": !Ref pEnvironmentLowerCase
          "bus:BusinessUnit": !Ref pDepartment

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: RtaBridgeLambda
    Properties:
      RetentionInDays: 3
      LogGroupName: !Sub "/aws/lambda/${RtaBridgeLambda}"

  RtaKinesisEventsToLambda:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn: RtaBridgeLambda
    Properties:
      EventSourceArn: !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${pInputStreamName}"
      FunctionName: !Ref RtaBridgeLambda
      StartingPosition: TRIM_HORIZON

  RtaBridgeLambdaPermissions:
    Type: AWS::Lambda::Permission
    DependsOn: RtaBridgeLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RtaBridgeLambda
      Principal: kinesis.amazonaws.com
      SourceArn: !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${pInputStreamName}"
