AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Collection of policies that allow the assumption of roles configured in other accounts in the organisation
Resources:
  ITAdministratorPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Groups:
        - IT_Administrator
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::745306361105:role/britishairways_connect_nonprod_admin'
              - 'arn:aws:iam::049293504011:role/common_nonprod_admin'
              - 'arn:aws:iam::595873495719:role/OliverPlay_Admin'
              - 'arn:aws:iam::943550779721:role/rpp_connect_prod_admin'
              - 'arn:aws:iam::581423163645:role/servicedesk_connect_prod_admin'
              - 'arn:aws:iam::907290942892:role/tradeuk_connect_nonprod_admin'
              - 'arn:aws:iam::443350248290:role/tradeuk_connect_prod_admin'
              - 'arn:aws:iam::808647995970:role/ccm_common_prod_admin'
              - 'arn:aws:iam::818313484557:role/MarkPlayAdmin'
              - 'arn:aws:iam::380325552120:role/assumableadministrator'
              - 'arn:aws:iam::114267387944:role/assumableadministrator'
              - 'arn:aws:iam::088954757811:role/PaulW_Play_Admin'
              - 'arn:aws:iam::555239192020:role/firstgroup_connect_nonprod_admin'
              - 'arn:aws:iam::857211198995:role/gassafe_connect_nonprod_admin'
              - 'arn:aws:iam::289601121201:role/gassafe_connect_prod_admin'
              - 'arn:aws:iam::082759818788:role/capitaeurope_nonprod_admin'
              - 'arn:aws:iam::512953984022:role/firstgroup_connect_prod_admin'
              - 'arn:aws:iam::992061356719:role/common_pipeline_admin'
      ManagedPolicyName: IT_Administrator_RoleAssumption_Policy
      Description: >-
        Allows the identity associated with this role to assume the role of britishairways_connect_nonprod_admin in account 745306361105.
  CapitaEuropeAdmin:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Groups:
        - CapitaEurope_Admin
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::082759818788:role/capitaeurope_nonprod_admin'
      ManagedPolicyName: CapitaEurope_Admin_Policy
      Description: >-
        Allows the identity associated with this role to assume the role of capita-europe-common-connect-nonprod in account 082759818788.
    DependsOn: CapitaEuropeAdminGroup
  CapitaEuropeAdminGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: CapitaEurope_Admin
  OrchestrationAdmin:
    Type: "AWS::IAM::ManagedPolicy"
    DependsOn: "OrchestrationAdminGroup"
    Properties:
      Description: "Allows the identity associated with this role to assume an administrator role in WebChat / Orchestration accounts."
      Groups:
        - "Orchestration_Admin"
        - "IT_Administrator"
      ManagedPolicyName: "Orchestration_Admin_Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam::895463101263:role/common_webchat_nonprod_admin"
              - "arn:aws:iam::455153666670:role/common_webchat_prod_admin"
              - "arn:aws:iam::338131171809:role/nationaltrust_webchat_nonprod_admin"
              - "arn:aws:iam::447342250202:role/nationaltrust_webchat_prod_admin"
  OrchestrationAdminGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Orchestration_Admin"