AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Template used to manage the groups and assign IAM policies to those groups; for use in the ccm credentials account.
Resources:

  ################################################################
  # Defines the policy and group for the AWS project team users. #
  ################################################################

  AWSProjectTeamGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: AWS_project_team

  AWSProjectTeamPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this policy to assume any of the specified roles in child accounts.
      ManagedPolicyName: "AWS_project_team_policy"
      Groups:
        - AWS_project_team
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::745306361105:role/britishairways_connect_nonprod_admin'
              - 'arn:aws:iam::049293504011:role/common_nonprod_admin'
              - 'arn:aws:iam::595873495719:role/OliverPlay_Admin'
              - 'arn:aws:iam::943550779721:role/rpp_connect_prod_admin'
              - 'arn:aws:iam::581423163645:role/servicedesk_connect_prod_admin'
              - 'arn:aws:iam::907290942892:role/tradeuk_connect_nonprod_admin'
              - 'arn:aws:iam::443350248290:role/tradeuk_connect_prod_admin'
              - 'arn:aws:iam::808647995970:role/ccm_common_prod_admin'
              - 'arn:aws:iam::818313484557:role/MarkPlayAdmin'
              - 'arn:aws:iam::380325552120:role/assumableadministrator'
              - 'arn:aws:iam::114267387944:role/assumableadministrator'
              - 'arn:aws:iam::088954757811:role/PaulW_Play_Admin'
              - 'arn:aws:iam::555239192020:role/firstgroup_connect_nonprod_admin'
              - 'arn:aws:iam::857211198995:role/gassafe_connect_nonprod_admin'
              - 'arn:aws:iam::289601121201:role/gassafe_connect_prod_admin'
              - 'arn:aws:iam::082759818788:role/capitaeurope_nonprod_admin'
              - 'arn:aws:iam::512953984022:role/firstgroup_connect_prod_admin'
              - 'arn:aws:iam::992061356719:role/common_pipeline_admin'
              - 'arn:aws:iam::177718949217:role/pendragon_connect_nonprod_admin'
              - 'arn:aws:iam::617836818304:role/common_pipeline_sandbox_admin'
              - 'arn:aws:iam::543667253492:role/lukehammond_admin'
              - 'arn:aws:iam::657888569302:role/RamnathBalakrishnan_Admin'
              - 'arn:aws:iam::556775351519:role/tradeuk_hackathon_admin'
    DependsOn: AWSProjectTeamGroup




   ###########################################################################################
   # Defines the policy and group for network administrators in the CCM credentials account. #
   ###########################################################################################

  NetworkAdminUserGroup:
     Type: 'AWS::IAM::Group'
     Properties:
       GroupName: Network_administrator

  NetworkAdminUserPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this role to undertake all DirectConnect actions in the common_prod
        account
      ManagedPolicyName: "Network_administrator_policy"
      Groups:
        - Network_administrator
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::808647995970:role/Network_admin_role'
    DependsOn: NetworkAdminUserGroup




   #############################################################################
   # Defines the policy and group for MI users in the CCM credentials account. #
   #############################################################################

  MIUserGroup:
     Type: 'AWS::IAM::Group'
     Properties:
       GroupName: MI_user

  MIUserPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this role to undertake various MI related actions in the common_prod and common_nonprod
        accounts
      ManagedPolicyName: "MI_user_policy"
      Groups:
        - MI_user
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::808647995970:role/MI_user_role'
              - 'arn:aws:iam::049293504011:role/MI_user_role'
    DependsOn: NetworkAdminUserGroup



  ########################################################################################
  # Defines the policy and group for user administrators in the CCM credentials account. #
  ########################################################################################

  CredentialsUserAdministratorGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Credentials_user_administrator

  CredentialsUserAdministratorPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this role to perform IAM and Organisations tasks inside the CCM
        credentials account.
      ManagedPolicyName: "Credentials_user_administrator_policy"
      Groups:
        - Credentials_user_administrator
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'iam:*'
              - 'organizations:*'
            Resource:
              - '*'
    DependsOn: CredentialsUserAdministratorGroup

  ########################################################################################
  # Defines the policy and group for administrators in the CCM credentials account. #
  ########################################################################################

  CredentialsAdministratorGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Credentials_administrator

  CredentialsAdministratorPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this role to perform unrestricted administrative tasks inside the CCM
        credentials account, but disallows the assumption of roles outside the account.
      ManagedPolicyName: "Credentials_administrator_policy"
      Groups:
        - Credentials_administrator
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            NotAction:
              - 'sts:*'
            Resource:
              - '*'
    DependsOn: CredentialsAdministratorGroup




  ######################################################################################################################
  # Defines the policy and group for allowing assumption of administrator access to the AWS organisation root account. #
  ######################################################################################################################

  BillingAdministratorGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Billing_administrator

  BillingAdministratorPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this role to assume any role within the billing account.
      ManagedPolicyName: "Billing_administrator_policy"
      Groups:
        - Billing_administrator
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::354340146682:role/*'
    DependsOn: BillingAdministratorGroup




  #########################################################################################################################
  # Defines the policy and group for allowing the assumption of a read-only role in the AWS organisation billing account. #
  #########################################################################################################################

  BillingReadOnlyGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Billing_read_only

  BillingReadOnlyPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows the identity which possesses this role to assume a read-only role within the billing account.
      ManagedPolicyName: "Billing_read_only_policy"
      Groups:
        - Billing_read_only
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::354340146682:role/common_billing_read'
    DependsOn: BillingReadOnlyGroup




  ################################################################################################################################
  # Define the policy and groups for allowing the assumption of roles for third party developers with access to our environment. #
  #     NOTE: Users in this group are prevented from assuming certain roles but will be allowed access through the use of        #
  #           user-attached policies (i.e. check IAM console to see the access each person in this group has.)                   #
  ################################################################################################################################

  ThirdPartyDevGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Third_party_developer

  ThirdPartyDevPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Prevents the identity which possesses this role from assuming administrative roles in the billing or
        credentials accounts.
      ManagedPolicyName: "Third_party_developer_policy"
      Groups:
        - Third_party_developer
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action:
              - 'sts:AssumeRole*'
            Resource:
              - 'arn:aws:iam::354340146682:role/*'
    DependsOn: ThirdPartyDevGroup



  ####################################################################################################################
  # Define a group into which Guest AWS Console users can be placed.                                                 #
  #        NOTE: Users in this group are not required to enable MFA, but are expressly forbidden from actions in the #
  #              credentials and billing accounts.                                                                   #
  ####################################################################################################################

  GuestGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Guest_user

  GuestPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Allows users within this group to manage their own credentials and disallows the assumption of roles inside
        the billing account.
      ManagedPolicyName: "Guest_user_policy"
      Groups:
        - Guest_user
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action:
              - 'sts:AssumeRole*'
            Resource:
              - 'arn:aws:iam::354340146682:role/*'
    DependsOn: GuestGroup




  ########################################################################################
  # Define a policy which requires users to have MFA enabled before they can do anything #
  ########################################################################################

  MultiFactorAuthGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: MFA_group

  MultiFactorAuthPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        Policy attached to groups which ensures that IAM users cannot undertake any action except those specified
        below until they have MFA applied to their IAM account.
      ManagedPolicyName: "MFA_policy"
      Groups:
        - MFA_group
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowViewAccountInfo"
            Effect: "Allow"
            Action:
              - "iam:GetAccountPasswordPolicy"
              - "iam:GetAccountSummary"
              - "iam:ListVirtualMFADevices"
            Resource: "*"
          - Sid: "AllowManageOwnPassword"
            Effect: "Allow"
            Action:
              - "iam:ChangePassword"
              - "iam:GetUser"
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Sid: "AllowManageOwnMFADevice"
            Effect: "Allow"
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:DeleteVirtualMFADevice"
              - "iam:DeactivateMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ListMFADevices"
              - "iam:ResyncMFADevice"
            Resource:
              - "arn:aws:iam::*:mfa/${aws:username}"
              - "arn:aws:iam::*:user/${aws:username}"
    DependsOn:
      - MultiFactorAuthGroup