AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Collection of policies that allow the assumption of roles configured in other accounts in the organisation
Resources:
  ITAdministratorPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Groups:
        - IT_Administrator
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::745306361105:role/britishairways_connect_nonprod_admin'
              - 'arn:aws:iam::049293504011:role/common_nonprod_admin'
              - 'arn:aws:iam::595873495719:role/OliverPlay_Admin'
              - 'arn:aws:iam::943550779721:role/rpp_connect_prod_admin'
              - 'arn:aws:iam::581423163645:role/servicedesk_connect_prod_admin'
              - 'arn:aws:iam::907290942892:role/tradeuk_connect_nonprod_admin'
              - 'arn:aws:iam::443350248290:role/tradeuk_connect_prod_admin'
              - 'arn:aws:iam::808647995970:role/ccm_common_prod_admin'
              - 'arn:aws:iam::818313484557:role/MarkPlayAdmin'
              - 'arn:aws:iam::380325552120:role/assumableadministrator'
              - 'arn:aws:iam::114267387944:role/assumableadministrator'
              - 'arn:aws:iam::088954757811:role/PaulW_Play_Admin'
              - 'arn:aws:iam::555239192020:role/firstgroup_connect_nonprod_admin'
              - 'arn:aws:iam::857211198995:role/gassafe_connect_nonprod_admin'
              - 'arn:aws:iam::289601121201:role/gassafe_connect_prod_admin'
              - 'arn:aws:iam::082759818788:role/capitaeurope_nonprod_admin'
              - 'arn:aws:iam::512953984022:role/firstgroup_connect_prod_admin'
              - 'arn:aws:iam::992061356719:role/common_pipeline_admin'
              - 'arn:aws:iam::177718949217:role/pendragon_connect_nonprod_admin'
              - "arn:aws:iam::617836818304:role/common_pipeline_sandbox_admin"
              - "arn:aws:iam::543667253492:role/lukehammond_admin"
              - "arn:aws:iam::657888569302:role/RamnathBalakrishnan_Admin"
      ManagedPolicyName: IT_Administrator_RoleAssumption_Policy
      Description: >-
        Allows the identity associated with this role to assume the role of britishairways_connect_nonprod_admin in account 745306361105.
  LukeHammond:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Groups:
        - Luke_Hammond_Admin
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::543667253492:role/lukehammond_admin'
      ManagedPolicyName: LukeHammond_Admin_Policy
      Description: >-
        Allows the identity associated with this role to assume the role of lukehammond_admin in account 543667253492.
    DependsOn: LukeHammondAdminGroup
  LukeHammondAdminGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Luke_Hammond_Admin
  CapitaEuropeAdmin:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Groups:
        - CapitaEurope_Admin
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource:
              - 'arn:aws:iam::082759818788:role/capitaeurope_nonprod_admin'
      ManagedPolicyName: CapitaEurope_Admin_Policy
      Description: >-
        Allows the identity associated with this role to assume the role of capita-europe-common-connect-nonprod in account 082759818788.
    DependsOn: CapitaEuropeAdminGroup
  CapitaEuropeAdminGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: CapitaEurope_Admin
  OrchestrationAdmin:
    Type: "AWS::IAM::ManagedPolicy"
    DependsOn: "OrchestrationAdminGroup"
    Properties:
      Description: "Allows the identity associated with this role to assume an administrator role in WebChat / Orchestration accounts."
      Groups:
        - "Orchestration_Admin"
        - "IT_Administrator"
      ManagedPolicyName: "Orchestration_Admin_Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam::895463101263:role/common_webchat_nonprod_admin"
              - "arn:aws:iam::455153666670:role/common_webchat_prod_admin"
              - "arn:aws:iam::338131171809:role/nationaltrust_webchat_nonprod_admin"
              - "arn:aws:iam::447342250202:role/nationaltrust_webchat_prod_admin"
  OrchestrationAdminGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Orchestration_Admin"
  ConnectReadOnlyGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Connect_ReadOnly"
  ConnectReadOnlyRole:
      Type: "AWS::IAM::ManagedPolicy"
      DependsOn: "ConnectReadOnlyGroup"
      Properties:
        Description: "Allows the identity associated with this role to assume a read-only role that allows access to AWS Connect and related services"
        Groups:
          - "Connect_ReadOnly"
        ManagedPolicyName: "Connect_ReadOnly_Policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "sts:AssumeRole"
              Resource:
                - "arn:aws:iam::857211198995:role/Connect_ReadOnly"
                - "arn:aws:iam::289601121201:role/Connect_ReadOnly"
  AthenaAdministratorGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Athena_Admin"
  AthenaAdminPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    DependsOn: "AthenaAdministratorGroup"
    Properties:
      Description: "Provides the assuming identity full access to Athena in the destination account"
      Groups:
        - "Athena_Admin"
      ManagedPolicyName: "Athena_Admin_Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam::289601121201:role/Athena_Admin"
              - "arn:aws:iam::857211198995:role/Athena_Admin"
  Athena_Machine_Access_Dev:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Allows Cross Account Access to Dev Athena Resources in common non-prod"
      ManagedPolicyName: "Athena_Machine_Access_Common_Dev"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam::049293504011:role/CA_MI_ATHENA_CCM_DEV"
  Athena_Machine_Access_Test:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Allows Cross Account Access to Test Athena Resources in common non-prod"
      ManagedPolicyName: "Athena_Machine_Access_Common_Test"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam::049293504011:role/CA_MI_ATHENA_CCM_TEST"
  Athena_Machine_Access_Prod:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Allows Cross Account Access to Prod Athena Resources in common prod"
      ManagedPolicyName: "Athena_Machine_Access_Common_Prod"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource:
              - "arn:aws:iam::808647995970:role/CA_MI_ATHENA_CCM_PROD"
