AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "CAPITA - Connect WIDGET - DDI Branch | Repo: ccm-connect-source/CAPITA/connect-widgets/common/ddi-branch/resources"
Parameters:
  pEnvironment:
      Type: String
      Default: DEV
      Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pClient:
    Type: String
    Description: Customer/Client identifier

Resources:

  # DynamoDB table used to hold DDI and AWS Connect Queue ARN key:value pairs
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "dynamodb-capita-${pDepartment}-connect-${pClient}-${pEnvironmentLowerCase}-${AWS::Region}-ddibranch"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: "DialledDDI"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "DialledDDI"
          KeyType: "HASH"

  DdiBranchFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "lmbdDdiBranchRead-${pDepartment}-${pEnvironment}"
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Timeout: 180
      CodeUri: ./../src/
      Environment:
        Variables:
          DynamoDBTableName: !Sub "dynamodb-capita-${pDepartment}-connect-${pClient}-${pEnvironmentLowerCase}-${AWS::Region}-ddibranch"
      Policies:
        - AWSLambdaRole
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamoDB:Scan"
              Resource: !GetAtt DynamoDBTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Action:
                - "logs:CreateLogGroup"
              Resource: "arn:aws:logs:*:*:*"
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Action:
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"
      Tags:
        "tech:ApplicationID": !Sub "capita-${pDepartment}-connect"
        "tech:Environment": !Ref pEnvironmentLowerCase
        "tech:ApplicationRole": "connect"
        "bus:BusinessUnit": !Ref pDepartment
        "bus:Business": !Ref pClient
    DependsOn: "DynamoDBTable"
