AWSTemplateFormatVersion: "2010-09-09"
Description: Basic account setup for Capita RTA web application

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase

Resources:

  CommonConnectS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting"
      LifecycleConfiguration: 
        Rules:
          -
            Id: agent-interval-removal
            Prefix: agent_interval
            Status: "Enabled"
            ExpirationInDays: 395
          -
            Id: queue-interval-removal
            Prefix: queue_interval
            Status: "Enabled"
            ExpirationInDays: 395
          -
            Id: contact-record-removal
            Prefix: contact_record
            Status: "Enabled"
            ExpirationInDays: 395
          -
            Id: query-result-removal
            Prefix: query-results
            Status: "Enabled"
            ExpirationInDays: 7
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-connect"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "tech:ApplicationRole"
            Value: reporting
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "sec:Compliance"
            Value: PII

  CommonConnectS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref "CommonConnectS3Bucket"
      PolicyDocument:
        Statement:
        -
          Sid: StmtID
          Effect: Allow
          Principal:
            AWS: "arn:aws:iam::907290942892:role/mi-ctr-firehose-role"
          Action:
          - s3:AbortMultipartUpload
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:PutObject
          - s3:PutObjectAcl
          Resource:
          - !GetAtt CommonConnectS3Bucket.Arn
          - !Sub
            - ${Arn}/*
            - { Arn: !GetAtt CommonConnectS3Bucket.Arn }
