AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA MI Cross-account role for Firehose

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pEnvironmentUpperCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, uppercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pCustomerReportingBucketArn:
    Type: String
    Description: Name of Customer S3 Bucket for raw MI reports
  pCommonReportingBucket:
    Type: String
    Description: S3 Bucket in the common account for transformed MI reports

Resources:
  CrossAccountFirehoseRole:
     Type: AWS::IAM::Role
     Properties:
       RoleName: !Sub "CA_MI_${pEnvironmentUpperCase}"
       AssumeRolePolicyDocument:
         Version: "2012-10-17"
         Statement:
           - Effect: "Allow"
             Action: "sts:AssumeRole"
             Principal:
               "Service": "firehose.amazonaws.com"
       Policies:
        - PolicyName: !Sub "reporting_buckets_${pEnvironmentLowerCase}"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - "glue:*"
              Effect: Allow
              Resource: "*"
            - Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
              - s3:PutObjectAcl
              Resource:
              - !Sub "arn:aws:s3:::${pCommonReportingBucket}"
              - !Sub "arn:aws:s3:::${pCommonReportingBucket}/*"
              - !Sub "${pCustomerReportingBucketArn}"
              - !Sub "${pCustomerReportingBucketArn}/*"
              Effect: Allow

            - Action:
              - logs:PutLogEvents
              Resource: "*"
              Effect: Allow

            - Action:
                - "kinesis:*"
              Resource: "*"
              Effect: Allow
            - Action:
                - kms:Decrypt
              Resource: "*"
              Effect: Allow

Outputs:
  oCrossAccountRoleArn:
    Value: !GetAtt CrossAccountFirehoseRole.Arn
