AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CAPITA MI Customer Reporting Bucket Modder

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pClient:
    Type: String
    Description: Customer/Client identifier
  pCustomerReportingBucketArn:
    Type: String
    Description: Customer reporting bucket Arn


Resources:
  CustomerReportingBucketModderLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lmbMiReportingModder-${pDepartment}-${pEnvironment}"
      Handler: lambda_handler.handler
      Runtime: python3.6
      Timeout: 180
      CodeUri: ../../../src/customer-bucket-modder/code/
      Policies: 
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "s3:*"
              Resource: !Ref pCustomerReportingBucketArn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iam:GetRole
                - iam:PassRole
              Resource: "*"
      Tags:
        "tech:ApplicationID": !Sub "capita-${pDepartment}-connect"
        "tech:Environment": !Ref pEnvironmentLowerCase
        "tech:ApplicationRole": "reporting"
        "bus:BusinessUnit": !Ref pDepartment
        "bus:Business": !Ref pClient

Outputs:
  oCustomerReportingBucketModderArn:
    Value: !GetAtt CustomerReportingBucketModderLambda.Arn

  