AWSTemplateFormatVersion: "2010-09-09"
Description: Basic account setup for Capita RTA web application

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase

Resources:

  AgentScheduleBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      # s3-ccm-prd-common-prod-agentschedule - added an extra 'capita' into bucket name
      BucketName: !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']]
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-rta-webapp"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "sec:Compliance"
            Value: PII



  LambdaDeploymentBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ['s3', 'capita', !Ref pDepartment, !Ref pEnvironmentLowerCase, 'lambdas', !Ref "AWS::Region"]]
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-rta-webapp"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "sec:Compliance"
            Value: PII

  # CommonMachineAgentStatusAccessRole:
  #   Type: AWS::IAM::Role
  #   Properties: 
  #     RoleName: !Join ["-", ['AgentStatusS3AccessRole'], !Ref pEnvironment]

  # CommonMachineAgentStatusAccessPolicy:
  #   Type: AWS::IAM::Policy
  #   Properties:
  #     PolicyName: !Join ["-", ['AgentStatusS3AccessPolicy'], !Ref pEnvironment]


  
Outputs:
  oAgentScheduleBucketArn:
    Value: !GetAtt AgentScheduleBucketS3.Arn
  oLambdaDeploymentBucketArn:
    Value: !GetAtt LambdaDeploymentBucketS3.Arn
