AWSTemplateFormatVersion: '2010-09-09'
Description: CAPITA Connect Call Recordings Bucket

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pClient:
    Type: String
    Description: Customer/Client identifier
  pExpirationCalls:
    Type: Number
    Default: 90
    Description: Expiration in days for call recordings


Resources:

  CallRecordingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-capita-${pDepartment}-connect-${pClient}-${pEnvironmentLowerCase}-${AWS::Region}-callrecordings"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        -
          Id: call-recordings-removal
          Status: Enabled
          ExpirationInDays: !Ref pExpirationCalls
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-connect"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "tech:ApplicationRole"
            Value: "reporting"
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "bus:Business"
            Value: !Ref pClient
        -
            Key: "sec:Compliance"
            Value: PII

Outputs:
  oCallRecordingBucketArn:
    Value: !GetAtt CallRecordingBucket.Arn
  oCallRecordingBucket:
    Value: !Ref CallRecordingBucket
