AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API setup for Capita Connect Web-Interface application

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pUserPoolArn:
    Type: String
    Description: Arn for the Cognito User Pool
  pClient:
    Type: String
    Description: Client name
  pS3BucketName:
    Type: String
    Description: S3 Bucket name where Lambda code for an API is stored
  pVariablesDBTable:
    Type: String
    Description: Name of the DynamoDB table which stores Variables Data
  pVariablesDBTableArn:
    Type: String
    Description: Arn for the DynamoDB table which stores Variables Data


Resources:

  WebInterfaceApiReadLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "Connect_WebInterface_GetVariables"
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Timeout: 180
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !Ref pVariablesDBTableArn
      CodeUri:
        Bucket: !Ref pS3BucketName
        Key: WebInterface_GetVariables.zip
      Environment:
        Variables:
          VariablesDB: !Ref pVariablesDBTable
          AUTH: true
      Tags:
          "tech:ApplicationID": !Sub "capita-${pDepartment}-web_interface-webapp"
          "tech:Environment": !Ref pEnvironmentLowerCase
          "bus:BusinessUnit": !Ref pDepartment
          "tech:ApplicationRole": "connect"
          "bus:Business": !Ref pClient

  WebInterfaceApiReadLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: WebInterfaceApiReadLambda
    Properties: 
      RetentionInDays: 3
      LogGroupName: !Sub "/aws/lambda/${WebInterfaceApiReadLambda}"

  WebInterfaceApiWriteLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Connect_WebInterface_SetVariables
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Timeout: 180
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !Ref pVariablesDBTableArn
      CodeUri:
        Bucket: !Ref pS3BucketName
        Key: WebInterface_SetVariables.zip
      Environment:
        Variables:
          VariablesDB: !Ref pVariablesDBTable
          AUTH: true
      Tags:
          "tech:ApplicationID": !Sub "capita-${pDepartment}-webinterface-webapp"
          "tech:Environment": !Ref pEnvironmentLowerCase
          "bus:BusinessUnit": !Ref pDepartment
          "tech:ApplicationRole": "connect"
          "bus:Business": !Ref pClient

  WebInterfaceApiWriteLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: WebInterfaceApiWriteLambda
    Properties: 
      RetentionInDays: 3
      LogGroupName: !Sub "/aws/lambda/${WebInterfaceApiWriteLambda}"

  WebInterfaceApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join ["", ["ConnectWebInterface-", !Ref pDepartment, "-", !Ref pEnvironment, "Api"]]
      Body:
        swagger: 2.0
        info:
          version: 1.0.0
          title: ConnectWebInterfaceApi
        paths:
          /webinterface:
            get:
              description: Invokes the get lambda function
              consumes:
                - application/json
              produces:
                - application/json
              security:
                - CognitoAuthorizer: []
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "401":
                  description: "401 response: unauthorised client"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "500":
                  description: "500 response: internal server error"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                  "401":
                    statusCode: 401
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                  "500":
                    statusCode: 500
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                uri: 
                  Fn::Join:
                    - ""
                    - - "arn:aws:apigateway:"
                      - !Ref AWS::Region
                      - ":lambda:path/2015-03-31/functions/"
                      - !GetAtt WebInterfaceApiReadLambda.Arn
                      - "/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws"
            post:
              description: Invokes the set lambda function
              consumes:
                - application/json
              produces:
                - application/json
              security:
                - CognitoAuthorizer: []
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "401":
                  description: "401 response: unauthorised client"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "500":
                  description: "500 response: internal server error"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                  "401":
                    statusCode: 401
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                  "500":
                    statusCode: 500
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                uri: 
                  Fn::Join:
                    - ""
                    - - "arn:aws:apigateway:"
                      - !Ref AWS::Region
                      - ":lambda:path/2015-03-31/functions/"
                      - !GetAtt WebInterfaceApiWriteLambda.Arn
                      - "/invocations"
                requestTemplates:
                  application/json: "{\n    \"variableName\": $input.json('$.variableName'),\n\"variableValue\": $input.json('$.variableValue')\n}"
                passthroughBehavior: "when_no_templates"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws"
            options:
              consumes:
                - application/json
              produces:
                - application/json
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
                "401":
                  description: "401 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
                "500":
                  description: "500 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
        securityDefinitions:
          CognitoAuthorizer:
            type: "apiKey"
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
              providerARNs:
                - !Ref pUserPoolArn
              type: "cognito_user_pools"


  WebInterfaceApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Prod deployment for Web-Interface API
      RestApiId: !Ref WebInterfaceApi
      StageName: prod
      

  WebInterfaceApiReadLambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebInterfaceApiReadLambda
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref WebInterfaceApi
            - "/*"

  WebInterfaceApiWriteLambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebInterfaceApiWriteLambda
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref WebInterfaceApi
            - "/*"

Outputs:
  oWebInterfaceApi:
    Value: !Ref WebInterfaceApi  