AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MI athena related resources for Common Account

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pCtrLocation:
    Type: String
    Default: "s3://s3-capita-ccm-connect-common-dev-reporting/contact_record/"
    Description: Name of bucket containing CTR data in Parquet format
  pQILocation:
    Type: String
    Default: "s3://s3-capita-ccm-connect-common-dev-reporting/queue_interval/"
    Description: Name of bucket containing Queue Interval data in Parquet format
  pAILocation:
    Type: String
    Default: "s3://s3-capita-ccm-connect-common-dev-reporting/agent_interval/"
    Description: Name of bucket containing Agent Interval data in Parquet format

Resources:
  AthenaMachineUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "machine-mi-athena-${pDepartment}-${pEnvironmentLowerCase}"
      Policies:
      - PolicyName: !Sub "access_athena_queries${pEnvironmentLowerCase}"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - "s3:*"
            Resource:
            - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting"
            - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting/*"
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/service-role/AWSQuicksightAthenaAccess"

  GlueDb:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Sub "${pDepartment}_connect_reporting_${pEnvironmentLowerCase}"
      CatalogId: !Ref AWS::AccountId

  GlueCtrTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDb
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Sub "contact_record"
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        PartitionKeys:
          - Name: clientname
            Type: string
          - Name: rowdate
            Type: string
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          Location: !Ref pCtrLocation
          SerdeInfo:
             Name: "serde-info"
             Parameters:
               serialization.format: 1
             SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Columns:
          -  Name: AWSAccountId
             Type: string
          -  Name: AWSContactTraceRecordFormatVersion
             Type: string
          -  Name: Agent
             Type: string
          -  Name: AgentConnectionAttempts
             Type: string
          -  Name: Attributes
             Type: string
          -  Name: Channel
             Type: string
          -  Name: ConnectedToSystemTimestamp
             Type: timestamp
          -  Name: ContactId
             Type: string
          -  Name: CustomerEndpoint
             Type: string
          -  Name: DisconnectTimestamp
             Type: timestamp
          -  Name: InitialContactId
             Type: string
          -  Name: InitiationMethod
             Type: string
          -  Name: InitiationTimestamp
             Type: timestamp
          -  Name: InstanceARN
             Type: string
          -  Name: LastUpdateTimestamp
             Type: timestamp
          -  Name: MediaStreams
             Type: string
          -  Name: NextContactId
             Type: string
          -  Name: PreviousContactId
             Type: string
          -  Name: Queue
             Type: string
          -  Name: Recording
             Type: string
          -  Name: Recordings
             Type: string
          -  Name: SystemEndpoint
             Type: string
          -  Name: TransferCompletedTimestamp
             Type: timestamp
          -  Name: TransferredToEndpoint
             Type: string

  GlueQueueIntervalTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDb
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Sub "queue_interval"
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        PartitionKeys:
          - Name: clientname
            Type: string
          - Name: rowdate
            Type: string
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          Location: !Ref pQILocation
          SerdeInfo:
            Name: "serde-info"
            Parameters:
              serialization.format: 1
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Columns:
            - Name: queue
              Type: string
            - Name: startinterval
              Type: timestamp
            - Name: endinterval
              Type: timestamp
            - Name: aftercontactworktime
              Type: int
            - Name: agentoncontacttime
              Type: int
            - Name: agentidletime
              Type: int
            - Name: averagequeueabandontime
              Type: int
            - Name: averageaftercontactworktime
              Type: int
            - Name: averagequeueanswertime
              Type: int
            - Name: averagehandletime
              Type: int
            - Name: averagecustomerholdtime
              Type: int
            - Name: averageagentinteractionandcustomerholdtime
              Type: int
            - Name: averageagentinteractiontime
              Type: int
            - Name: contactsabandoned
              Type: int
            - Name: contactsabandonedin15seconds
              Type: int
            - Name: contactsabandonedin20seconds
              Type: int
            - Name: contactsabandonedin25seconds
              Type: int
            - Name: contactsabandonedin30seconds
              Type: int
            - Name: contactsabandonedin45seconds
              Type: int
            - Name: contactsabandonedin60seconds
              Type: int
            - Name: contactsabandonedin90seconds
              Type: int
            - Name: contactsabandonedin120seconds
              Type: int
            - Name: contactsabandonedin180seconds
              Type: int
            - Name: contactsabandonedin240seconds
              Type: int
            - Name: contactsabandonedin300seconds
              Type: int
            - Name: contactsabandonedin600seconds
              Type: int
            - Name: contactsagenthungupfirst
              Type: int
            - Name: contactsconsulted
              Type: int
            - Name: contactshandled
              Type: int
            - Name: contactshandledincoming
              Type: int
            - Name: contactshandledoutbound
              Type: int
            - Name: callbackcontactshandled
              Type: int
            - Name: contactsputonhold
              Type: int
            - Name: contactsholddisconnect
              Type: int
            - Name: contactsholdagentdisconnect
              Type: int
            - Name: contactsholdcustomerdisconnect
              Type: int
            - Name: contactsincoming
              Type: int
            - Name: callbackcontacts
              Type: int
            - Name: contactsansweredin15seconds
              Type: int
            - Name: contactsansweredin20seconds
              Type: int
            - Name: contactsansweredin25seconds
              Type: int
            - Name: contactsansweredin30seconds
              Type: int
            - Name: contactsansweredin45seconds
              Type: int
            - Name: contactsansweredin60seconds
              Type: int
            - Name: contactsansweredin90seconds
              Type: int
            - Name: contactsansweredin120seconds
              Type: int
            - Name: contactsansweredin180seconds
              Type: int
            - Name: contactsansweredin240seconds
              Type: int
            - Name: contactsansweredin300seconds
              Type: int
            - Name: contactsansweredin600seconds
              Type: int
            - Name: contactsqueued
              Type: int
            - Name: contactstransferredin
              Type: int
            - Name: contactstransferredout
              Type: int
            - Name: contactstransferredoutinternal
              Type: int
            - Name: contactstransferredoutexternal
              Type: int
            - Name: contactstransferredinfromqueue
              Type: int
            - Name: contactstransferredoutfromqueue
              Type: int
            - Name: customerholdtime
              Type: int
            - Name: agentanswerrate
              Type: int
            - Name: maximumqueuedtime
              Type: int
            - Name: contactsmissed
              Type: int
            - Name: contacthandletime
              Type: int
            - Name: contactflowtime
              Type: int
            - Name: occupancy
              Type: int
            - Name: servicelevel15seconds
              Type: string
            - Name: servicelevel20seconds
              Type: string
            - Name: servicelevel25seconds
              Type: string
            - Name: servicelevel30seconds
              Type: string
            - Name: servicelevel45seconds
              Type: string
            - Name: servicelevel60seconds
              Type: string
            - Name: servicelevel90seconds
              Type: string
            - Name: servicelevel120seconds
              Type: string
            - Name: servicelevel180seconds
              Type: string
            - Name: servicelevel240seconds
              Type: string
            - Name: servicelevel300seconds
              Type: string
            - Name: servicelevel600seconds
              Type: string
            - Name: agentinteractionandholdtime
              Type: int
            - Name: agentinteractiontime
              Type: int
            - Name: averageoutboundagentinteractiontime
              Type: int
            - Name: averageoutboundaftercontactworktime
              Type: int

  GlueAgentIntervalTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDb
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Sub "agent_interval"
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        PartitionKeys:
          - Name: clientname
            Type: string
          - Name: rowdate
            Type: string
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          Location: !Ref pAILocation
          SerdeInfo:
            Name: "serde-info"
            Parameters:
              serialization.format: 1
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Columns:
          - Name: startinterval
            Type: timestamp
          - Name: endinterval
            Type: timestamp
          - Name: agentname
            Type: string
          - Name: agentfirstname
            Type: string
          - Name: agentlastname
            Type: string
          - Name: aftercontactworktime
            Type: int
          - Name: agentoncontacttime
            Type: int
          - Name: agentidletime
            Type: int
          - Name: nonproductivetime
            Type: int
          - Name: averageaftercontactworktime
            Type: int
          - Name: contactsagenthungupfirst
            Type: int
          - Name: contactsconsulted
            Type: int
          - Name: contactshandled
            Type: int
          - Name: contactshandledincoming
            Type: int
          - Name: contactshandledoutbound
            Type: int
          - Name: callbackcontactshandled
            Type: int
          - Name: contactsputonhold
            Type: int
          - Name: contactsholddisconnect
            Type: int
          - Name: contactsholdagentdisconnect
            Type: int
          - Name: contactsholdcustomerdisconnect
            Type: int
          - Name: contactsincoming
            Type: int
          - Name: callbackcontacts
            Type: int
          - Name: contactsqueued
            Type: int
          - Name: contactstransferredin
            Type: int
          - Name: contactstransferredout
            Type: int
          - Name: contactstransferredoutinternal
            Type: int
          - Name: contactstransferredoutexternal
            Type: int
          - Name: contactstransferredinfromqueue
            Type: int
          - Name: contactstransferredoutfromqueue
            Type: int
          - Name: errorstatustime
            Type: int
          - Name: customerholdtime
            Type: int
          - Name: agentanswerrate
            Type: int
          - Name: maximumqueuedtime
            Type: int
          - Name: contactsmissed
            Type: int
          - Name: contacthandletime
            Type: int
          - Name: contactflowtime
            Type: int
          - Name: occupancy
            Type: int
          - Name: servicelevel15seconds
            Type: string
          - Name: servicelevel20seconds
            Type: string
          - Name: servicelevel25seconds
            Type: string
          - Name: servicelevel30seconds
            Type: string
          - Name: servicelevel45seconds
            Type: string
          - Name: servicelevel60seconds
            Type: string
          - Name: servicelevel90seconds
            Type: string
          - Name: servicelevel120seconds
            Type: string
          - Name: servicelevel180seconds
            Type: string
          - Name: servicelevel240seconds
            Type: string
          - Name: servicelevel300seconds
            Type: string
          - Name: servicelevel600seconds
            Type: string
          - Name: onlinetime
            Type: int
          - Name: agentinteractionandholdtime
            Type: int
          - Name: agentinteractiontime
            Type: int
          - Name: averageoutboundagentinteractiontime
            Type: int
          - Name: averageoutboundaftercontactworktime
            Type: int
          - Name: breaktime
            Type: int
          - Name: lunchtime
            Type: int
          - Name: mentortime
            Type: int
          - Name: admintime
            Type: int
          - Name: trainingtime
            Type: int
          - Name: meetingtime
            Type: int
          - Name: onetoonetime
            Type: int
          - Name: outboundtime
            Type: int
          - Name: special1time
            Type: int
          - Name: outboundagentinteractiontime
            Type: int
          - Name: outboundagentaftercontactworktime
            Type: int
