AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CAPITA MI Glue DB partitioner for Agent Interval, Queue Interval and Contact Records

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pClients:
    Type: String
    Description: Customer/Client identifier
  pGlueDb:
    Type: String
    Description: Glue DB for Common reporting
  pTables:
    Type: String
    Description: Comma-delimited list of table names
  pCommonReportingBucket:
    Type: String
    Description: Common reporting bucket name

Resources:
  PartitionerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lmbMiPartitioner-${pDepartment}-${pEnvironment}"
      Handler: lambda_handler.handler
      Runtime: python3.6
      Timeout: 180
      CodeUri: ../../../src/partition-loader/code/
      Environment:
        Variables:
          DB: !Ref pGlueDb
          TABLES: !Ref pTables
          BUCKET: !Ref pCommonReportingBucket
          CLIENTS: !Ref pClients
      Policies: 
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "athena:*"
              Resource: "*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "glue:*"
              Resource: "*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "s3:*"
              Resource: !Sub "arn:aws:s3:::${pCommonReportingBucket}"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iam:GetRole
                - iam:PassRole
              Resource: "*"
      Tags:
        "tech:ApplicationID": !Sub "capita-${pDepartment}-connect"
        "tech:Environment": !Ref pEnvironmentLowerCase
        "tech:ApplicationRole": "reporting"
        "bus:BusinessUnit": !Ref pDepartment

  Schedule:
    Type: AWS::Events::Rule
    DependsOn: PartitionerLambda
    Properties:
      ScheduleExpression: "cron(1 0 * * ? *)"
      State: ENABLED
      Targets:
      - Arn: !GetAtt PartitionerLambda.Arn
        Id: paritioner_update
        Input: '{}'

  SchedulePermission:
    Type: AWS::Lambda::Permission
    DependsOn: Schedule
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PartitionerLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Schedule.Arn


Outputs:
  oPartitionerLambdaArn:
    Value: !GetAtt PartitionerLambda.Arn

