AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA MI Common Bucket Policy Update

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pCommonReportingBucket:
    Type: String
    Description: Name of common reporting Bucket

Resources:

  CommonConnectS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref pCommonReportingBucket
      PolicyDocument:
        Statement:
          # Using new generic cross-account role: CA_MI_PROD
        - Effect: Allow
          Principal:
            # First Group MI Role
            AWS: !Sub "arn:aws:iam::512953984022:role/CA_MI_PROD"
          Action:
            - s3:*
          Resource:
            - !Sub "arn:aws:s3:::${pCommonReportingBucket}"
            - !Sub "arn:aws:s3:::${pCommonReportingBucket}/*"
        - Effect: Allow
          Principal:
            # TradeUK MI Role
            AWS: "arn:aws:iam::443350248290:role/CA_MI_PROD"
          Action:
            - s3:*
          Resource:
            - !Sub "arn:aws:s3:::${pCommonReportingBucket}"
            - !Sub "arn:aws:s3:::${pCommonReportingBucket}/*"
