AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA MI Common Bucket Policy Update

Parameters:
  pEnvironment:
    Type: String
    Default: Test
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: test
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pCommonReportingBucket:
    Type: String
    Description: Name of common reporting Bucket

Resources:

  CommonConnectS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref pCommonReportingBucket
      PolicyDocument:
        Statement:
        # Using new generic cross-account role: CA_MI_TEST
        -
          Effect: Allow
          Principal:
            # First Group MI Role
            AWS: !Sub "arn:aws:iam::555239192020:role/CA_MI_TEST"
          Action:
          - s3:*
          Resource:
          - !Sub "arn:aws:s3:::${pCommonReportingBucket}"
          - !Sub "arn:aws:s3:::${pCommonReportingBucket}/*"
        -
          Effect: Allow
          Principal:
            # TradeUK MI Role
            AWS: "arn:aws:iam::907290942892:role/CA_MI_TEST"
          Action:
          - s3:*
          Resource:
          - !Sub "arn:aws:s3:::${pCommonReportingBucket}"
          - !Sub "arn:aws:s3:::${pCommonReportingBucket}/*"
        -
          Effect: Allow
          Principal:
            # GasSafe Test MI Role
            AWS: "arn:aws:iam::857211198995:role/CA_MI_TEST"
          Action:
          - s3:*
          Resource:
          - !Sub "arn:aws:s3:::${pCommonReportingBucket}"
          - !Sub "arn:aws:s3:::${pCommonReportingBucket}/*"
