AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MI athena related resources for Common Account

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase

Resources:
  AthenaMachineUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "machine-mi-athena-${pDepartment}-${pEnvironmentLowerCase}"
      Policies:
      - PolicyName: !Sub "access_athena_queries${pEnvironmentLowerCase}"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - "s3:*"
            Resource:
            - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting"
            - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting/*"
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/service-role/AWSQuicksightAthenaAccess"
