AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA Connect Agent Events Stack

Parameters:
  pCustomerReportBucket:
    Type: String
    Description: Name of Customer S3 Bucket to trigger lambda
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pClient:
    Type: String
    Description: Customer/Client identifier
  pKmsKeyId:
    Type: String
    Description: CMK KMS Key ID to use to encrypt Kinesis Stream

Resources:

  AgentEventsKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name:
        !Sub "ks-${pDepartment}-agent-events-${pEnvironmentLowerCase}"
      ShardCount: 1
      StreamEncryption:
        EncryptionType: KMS
        KeyId: !Ref pKmsKeyId
      Tags:
        - Key: tech:ApplicationID
          Value:
            !Sub "capita-${pDepartment}-connect"
        - Key: tech:Environment
          Value: !Ref pEnvironmentLowerCase
        - Key: sec:Compliance
          Value: PII
        - Key: bus:BusinessUnit
          Value: !Ref pDepartment
        - Key: bus:ClientName
          Value: !Ref pClient


Outputs:
  oAgentEventsStream:
    Value: !Ref AgentEventsKinesisStream
