AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA Connect Customer Lambda Deployment Bucket

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pRegion:
    Type: String
    Description: Region to be added as a suffix to bucket name
  pClient:
    Type: String
    Description: Client name

Resources:
  LambdaDeploymentS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-capita-${pDepartment}-connect-${pClient}-${pEnvironmentLowerCase}-${pRegion}-lambdas"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-connect-${pClient}"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "tech:ApplicationRole"
            Value: reporting
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment

Outputs:
  oConnectBucket:
    Value: !Ref LambdaDeploymentS3Bucket
