AWSTemplateFormatVersion: '2010-09-09'
Description: CAPITA MI Customer reporting bucket

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pClient:
    Type: String
    Description: Customer/Client identifier
  pExpirationReports:
    Type: Number
    Default: 30
    Description: Expiration after given number of days for all reports
  pExpirationCTRs:
    Type: Number
    Default: 30
    Description: Expiration after given number of days for raw ctr records
  pExpirationAgentEvents:
    Type: Number
    Default: 30
    Description: Expiration after given number of days for raw agent events


Resources:

  ReportingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-capita-${pDepartment}-connect-${pClient}-${pEnvironmentLowerCase}-${AWS::Region}-reporting"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        -
          Id: raw-ctr-removal
          Status: Enabled
          Prefix: raw-ctr
          ExpirationInDays: !Ref pExpirationCTRs
        -
          Id: raw-agentevents-removal
          Status: Enabled
          Prefix: raw-agentevents
          ExpirationInDays: !Ref pExpirationAgentEvents
        -
          Id: reports-removal
          Status: Enabled
          Prefix: reports
          ExpirationInDays: !Ref pExpirationReports
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-connect"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "tech:ApplicationRole"
            Value: "reporting"
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "bus:Business"
            Value: !Ref pClient
        -
            Key: "sec:Compliance"
            Value: PII

Outputs:
  oCustomerReportingBucketArn:
    Value: !GetAtt ReportingBucket.Arn
