version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.6
  pre_build:
    commands:
       - chmod +x CAPITA/pipelines/scripts/assume_role.sh
       - ./CAPITA/pipelines/scripts/assume_role.sh "CAPITA/pipelines/config/${CONFIG}.conf" "${ENV}"

  build:
    commands:
      - echo "Building / updating AWS Connect Widgets"
      - for f in $(find ./CAPITA/ -type f -regex ".*/pipeline-deployer.sh"); do chmod +x "$f"; done
      - cd CAPITA/pipelines/modules/aws-connect-widgets
      - if [ ! ${MODULE} ]; then MODULE='all'; fi
      - ./pipeline-deployer.sh ccm $ENV $CONFIG $MODULE
