CREATE OR REPLACE VIEW contact_record_view AS
SELECT
  "rowdate"
, "clientname"
, CAST("json_extract_scalar"("agent", '$.aftercontactworkduration') AS bigint) "aftercontactworkduration"
, "json_extract_scalar"("agent", '$.aftercontactworkendtimestamp') "aftercontactworkendtimestamp"
, "json_extract_scalar"("agent", '$.aftercontactworkstarttimestamp') "aftercontactworkstarttimestamp"
, CAST("json_extract_scalar"("agent", '$.agentinteractionduration') AS bigint) "agentinteractionduration"
, "json_extract_scalar"("agent", '$.connectedtoagenttimestamp') "connectedtoagenttimestamp"
, CAST("json_extract_scalar"("agent", '$.customerholdduration') AS bigint) "customerholdduration"
, "json_extract_scalar"("agent", '$.hierarchygroups') "hierarchygroups"
, CAST("json_extract_scalar"("agent", '$.longestholdduration') AS bigint) "longestholdduration"
, CAST("json_extract_scalar"("agent", '$.numberofholds') AS bigint) "numberofholds"
, "json_extract_scalar"("agent", '$.routingprofile.name') "routingprofilename"
, "json_extract_scalar"("agent", '$.username') "username"
, CAST("agentconnectionattempts" AS bigint) "agentconnectionattempts"
, "json_extract_scalar"("attributes", '$.attributesevacuation') "attributesevacuation"
, "json_extract_scalar"("attributes", '$.dynamiccallerid') "dynamiccallerid"
, "channel"
, "connectedtosystemtimestamp"
, "contactid"
, "json_extract_scalar"("customerendpoint", '$.address') "customeraddress"
, "json_extract_scalar"("customerendpoint", '$.type') "customertype"
, "disconnecttimestamp"
, "initialcontactid"
, "initiationmethod"
, "initiationtimestamp"
, "lastupdatetimestamp"
, "nextcontactid"
, "previouscontactid"
, "json_extract_scalar"("queue", '$.dequeuetimestamp') "queuedequeuetimestamp"
, CAST("json_extract_scalar"("queue", '$.duration') AS bigint) "queueduration"
, "json_extract_scalar"("queue", '$.enqueuetimestamp') "queueenqueuetimestamp"
, "json_extract_scalar"("queue", '$.name') "queuename"
, "json_extract_scalar"("recording", '$.deletionreason') "recordingdeletionreason"
, "json_extract_scalar"("recording", '$.location') "recordinglocation"
, "json_extract_scalar"("recording", '$.status') "recordingstatus"
, "json_extract_scalar"("recording", '$.type') "recordingtype"
, "json_extract_scalar"("systemendpoint", '$.address') "systemendpointaddress"
, "json_extract_scalar"("systemendpoint", '$.type') "systemendpointtype"
, "transfercompletedtimestamp"
, "transferredtoendpoint"
FROM
  ccm_connect_reporting_prod.contact_record
