AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a role in the target account which can be assumed from the credentials account (620730210164) to provide administrator level access"
Parameters:
  pClient:
    Type: "String"
    Description: "Lowercase client name e.g. tradeuk"
  pEnv:
    Type: "String"
    Description: "The desired name of the role you are creating"
    AllowedValues:
      - "nonprod"
      - "prod"
Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub "${pClient}_connect_${pEnv}_admin"
      Policies:
        - PolicyName: "AssumableAdmin"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: '*'
                Resource: '*'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              # 620730210164 is the CCM credentials account
              AWS:
                - 'arn:aws:iam::620730210164:root'
            Action:
              - 'sts:AssumeRole'
            Condition:
              BoolIfExists:
                'aws:MultiFactorAuthPresent': "true"