AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a role in the target account which can be assumed from the CCM credentials account (620730210164) to access to Athena and other MI resources"
Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "MI_user_role"
      Policies:
        - PolicyName: "MI_user_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                - 'athena:*'
                - 's3:*'
                - 'glue:*'
                - 'kinesis:*'
                Resource: '*'
              - Effect: 'Deny'
                Action: 's3:Delete*'
                Resource: '*'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - 'arn:aws:iam::620730210164:root'
            Action:
              - 'sts:AssumeRole'
            Condition:
              BoolIfExists:
                'aws:MultiFactorAuthPresent': "true"