AWSTemplateFormatVersion: "2010-09-09"
Description: CAPITA MI Health Checker Alarms

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pTopicArn:
    Type: String
    Description: ARN to the SNS Topic for health check alarms

Resources:

  AgentIntervalsFreshnessAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Detects if Agent Interval reports are stale
      AlarmActions:
        - !Ref pTopicArn
      MetricName: Freshness
      Namespace: CAPITA/MI
      Dimensions:
        - Name: ReportCategory
          Value: AgentIntervalReports
      Statistic: SampleCount
      Threshold: 45
      Period: '60'
      EvaluationPeriods: '1'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore

  AgentIntervalsMissingDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Detects if Agent Interval reports are missing
      AlarmActions:
        - !Ref pTopicArn
      MetricName: MissingData
      Namespace: CAPITA/MI
      Dimensions:
        - Name: ReportCategory
          Value: AgentIntervalReports
      Statistic: SampleCount
      Threshold: 1
      Period: '60'
      EvaluationPeriods: '1'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore

  QueueIntervalsFreshnessAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Detects if Queue Interval reports are stale
      AlarmActions:
        - !Ref pTopicArn
      MetricName: Freshness
      Namespace: CAPITA/MI
      Dimensions:
        - Name: ReportCategory
          Value: QueueIntervalReports
      Statistic: SampleCount
      Threshold: 45
      Period: '60'
      EvaluationPeriods: '1'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore

  QueueIntervalsMissingDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Detects if Queue Interval reports are missing
      AlarmActions:
        - !Ref pTopicArn
      MetricName: MissingData
      Namespace: CAPITA/MI
      Dimensions:
        - Name: ReportCategory
          Value: QueueIntervalReports
      Statistic: SampleCount
      Threshold: 1
      Period: '60'
      EvaluationPeriods: '1'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore

