AWSTemplateFormatVersion: "2010-09-09"
Description: Basic account setup for Capita RTA web application

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming, lower case
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase

Resources:

  LambdaDeploymentBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-capita-${pDepartment}-${pEnvironmentLowerCase}-lambdas-${AWS::Region}"
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-rta-webapp"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "sec:Compliance"
            Value: PII

  MachineUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "machine-rta-${pDepartment}-${pEnvironmentLowerCase}"
      Policies:
      - PolicyName: !Sub "access_schedule_bucket_only_${pEnvironmentLowerCase}"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - "s3:*"
            Resource:
            - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-common-${pEnvironmentLowerCase}-rta-agentschedules"
            - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-common-${pEnvironmentLowerCase}-rta-agentschedules/*"
  

Outputs:
  oLambdaDeploymentBucketArn:
    Value: !GetAtt LambdaDeploymentBucketS3.Arn
  oMachineUser:
    Value: !Ref MachineUser
  oMachineUserArn:
    Value: !GetAtt MachineUser.Arn
