AWSTemplateFormatVersion: '2010-09-09'
Description: Scheduled special Heart Beat for RTA
Parameters:
  pDepartment:
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
    Type: String
  pEnvironment:
    Default: DEV
    Description: Environment label to apply to resources naming
    Type: String
  pEnvironmentLowerCase:
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
    Type: String
  pStartSchedule:
    Default: cron(0 6 * * ? *)
    Description: Cron schedule for starting the heart beats
    Type: String
  pStopSchedule:
    Default: cron(0 22 * * ? *)
    Description: Cron schedule for stopping the heart beats
    Type: String
  pTargetLambdaArn:
    Description: Arn for the target lambda
    Type: String
Resources:
  HeartBeat:
    Properties:
      ScheduleExpression: rate(1 minute)
      State: DISABLED
      Targets:
      - Arn:
          Ref: pTargetLambdaArn
        Id: heartbeats
        Input: '{"EventType":"SP_HEART_BEAT"}'
    Type: AWS::Events::Rule
  HeartBeatsToLambdaPermission:
    DependsOn:
    - HeartBeat
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: pTargetLambdaArn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - HeartBeat
        - Arn
    Type: AWS::Lambda::Permission
  ScheduleHeartBeatsLambda:
    Properties:
      CodeUri: ../src/heartbeat/code
      Environment:
        Variables:
          HB:
            Ref: HeartBeat
          LOGGING_LEVEL: '20'
      FunctionName:
        Fn::Sub: lmbRtaHbScheduler-${pDepartment}-${pEnvironment}
      Handler: lambda_handler.handler
      Policies:
      - AWSLambdaExecute
      - CloudWatchEventsFullAccess
      Runtime: python3.6
      Timeout: 180
    Type: AWS::Serverless::Function
  StartHeartBeatSchedule:
    Properties:
      ScheduleExpression:
        Ref: pStartSchedule
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - ScheduleHeartBeatsLambda
          - Arn
        Id: start-heartbeats
        Input: '{"schedule": "start"}'
    Type: AWS::Events::Rule
  StartSchedulePermission:
    DependsOn:
    - StartHeartBeatSchedule
    - ScheduleHeartBeatsLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ScheduleHeartBeatsLambda
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - StartHeartBeatSchedule
        - Arn
    Type: AWS::Lambda::Permission
  StopHeartBeatSchedule:
    Properties:
      ScheduleExpression:
        Ref: pStopSchedule
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - ScheduleHeartBeatsLambda
          - Arn
        Id: stop-heartbeats
        Input: '{"schedule": "stop"}'
    Type: AWS::Events::Rule
  StopSchedulePermission:
    DependsOn:
    - StopHeartBeatSchedule
    - ScheduleHeartBeatsLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ScheduleHeartBeatsLambda
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - StopHeartBeatSchedule
        - Arn
    Type: AWS::Lambda::Permission
Transform: AWS::Serverless-2016-10-31