AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Verify lambda setup for Capita RTA web application

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase
  pOutputFilePath:
    Type: String
    Description: File path and name of Output file in input s3 bucket
  pAlarmConfigFilePath:
    Type: String
    Description: File path and name of Alarm Config in input s3 bucket

Resources:

  RtaVerifyLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["", ["lmbRtaVerify", "-", !Ref pDepartment, "-", !Ref pEnvironment]]
      Handler: lambda_handler.handler
      Runtime: python3.6
      Timeout: 180
      CodeUri: ../src/verify/code/
      Policies: 
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Join ["", ['arn:aws:s3:::', !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']], "/*"]]
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Join ["", ['arn:aws:s3:::', !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']], "/*"]]
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref RtaVerifySnsTopic
      Environment:
        Variables:
          input_s3_bucket: !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']]
          output_file_path: !Ref pOutputFilePath
          output_s3_bucket: !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']]
          alarm_config_file_path: !Ref pAlarmConfigFilePath
      Tags:
          "tech:ApplicationID": !Sub "capita-${pDepartment}-rta-webapp"
          "tech:Environment": !Ref pEnvironmentLowerCase
          "bus:BusinessUnit": !Ref pDepartment

  RtaApiLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: RtaVerifyLambda
    Properties: 
      RetentionInDays: 3
      LogGroupName: !Sub "/aws/lambda/${RtaVerifyLambda}"

  RtaVerifyLambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RtaVerifyLambda
      Principal: s3.amazonaws.com
      SourceArn: !Join ["", ['arn:aws:s3:::', !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']]]]

  AgentScheduleBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      # s3-capita-ccm-common-test-rta-agentschedules
      # s3-ccm-prd-common-prod-agentschedule - added an extra 'capita' into bucket name
      BucketName: !Join ["-", ['s3', 'capita', !Ref pDepartment, 'common', !Ref pEnvironmentLowerCase, 'rta-agentschedules']]
      NotificationConfiguration: 
        LambdaConfigurations: 
          -
            Event: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  -
                    Name: prefix
                    Value: uploads/
            Function:
              !GetAtt RtaVerifyLambda.Arn
      Tags:
        -
            Key: "tech:ApplicationID"
            Value: !Sub "capita-${pDepartment}-rta-webapp"
        -
            Key: "tech:Environment"
            Value: !Ref pEnvironmentLowerCase
        -
            Key: "bus:BusinessUnit"
            Value: !Ref pDepartment
        -
            Key: "sec:Compliance"
            Value: PII
  
  RtaVerifySnsTopic:
    Type: AWS::SNS::Topic

Outputs:
  oRtaScheduleBucketName:
    Value: !Ref AgentScheduleBucketS3
  oRtaScheduleBucketName:
    Value: !Ref AgentScheduleBucketS3