AWSTemplateFormatVersion: "2010-09-09"
Description: Cross Account Roles For Access From Credentials Account

Parameters:
  pEnvironment:
    Type: String
    Default: DEV
    Description: Environment label to apply to resources naming
  pEnvironmentLowerCase:
    Type: String
    Default: dev
    Description: Environment label to apply to resources naming, lowercase
  pDepartmentUpper:
    Type: String
    Default: CCM
    Description: Department identifier for unique bucket naming, uppercase
  pDepartment:
    Type: String
    Default: ccm
    Description: Department identifier for unique bucket naming, lowercase


Resources:
  AthenaMachineCARole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "CA_MI_ATHENA_${pDepartmentUpper}_${pEnvironment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal: 
              AWS: "arn:aws:iam::620730210164:root"
            Condition:
              StringEquals: 
                aws:username: !Sub "machine-mi-athena-${pDepartment}-${pEnvironmentLowerCase}"
      Policies:
        -
          PolicyName: !Sub "access_athena_queries${pEnvironmentLowerCase}"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            -
              Effect: Allow
              Action: 
              - "s3:*"
              Resource:
              - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting"
              - !Sub "arn:aws:s3:::s3-capita-${pDepartment}-connect-common-${pEnvironmentLowerCase}-reporting/*"
              - "arn:aws:s3:::timebands"
              - "arn:aws:s3:::timebands/*"
              - "arn:aws:s3:::timebandits"
              - "arn:aws:s3:::timebandits/*"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSQuicksightAthenaAccess"
